name = "modernXmin"
license = "MIT"
licenselink = ""
description = "Modern eXtremely Minimal Hugo theme"
homepage = ""
demosite = ""
tags = ["minimal", "blog", "personal", "clean", "simple", "starter", "minimalist", "testing"]
features = ["blog"]
min_version = "0.146.0"

[author]
  name = ""
  homepage = ""
